### PR TITLE
Ddm3d fix 31may2023

### PR DESCRIPTION
**Pull request by sergeynk**
### HDDM-3D fix

**Contact:**
[Sergey Napelenok](mailto:napelenok.sergey@epa.gov), U.S. Environmental Protection Agency

**Type of code change:**
Bug fix and documentation

**Description of changes:**
A small bug made its way into the chemistry routines that calculated 2nd order sensitivities (HDDM-3D) resulting in erroneous output for these parameters. Additionally, there are some runtime errors in the log files associated with writing out deposition sensitivity output. Finally, dry deposition sensitivities were not written out correctly.

Documentation updates are pulled from the main (5.4) branch.  These updates keep the documentation in the 5.4+ and main branches in sync. 

**Issue:**
If this resolves a known issue, include the link to the GitHub Issue number.

**Summary of Impact:**
2nd order sensitivities will now provide correct output and the log files will no longer display error messages about deposition sensitivities. Sensitivity of dry depositions will now output correctly past the 1st parameter.

**Tests conducted:**
Standard BLDCHECK test was conducted for 2016 SEBENCH for the 3 compilers and the debug mode in each.  Base CMAQ concentrations were found to be not impacted by code changes.  2nd order sensitivities were found to be more stable.  Deposition and log files were correctly written.

### CODE REVIEW

**Review by fisidi — APPROVED** [review]
@sergeynk thanks for putting this change in. When testing the code changes on the hemispheric domain with 2018 emissions/meteorology, the current 5.4+ branch produces extremely high second order DDM sensitivities (see figure below). Fixing the code with the changes in this pull request corrects these sensitivities, producing much more reasonable sensitivities. It should be noted, the first order sensitivities for both runs are exactly identical. 



**Figure 1: O3 second order sens produced with bugged code**

image

**Figure 2: O3 second order sens produced with bug fixed code**

image

**Review by kmfoley — APPROVED** [review]

**Comment by bandaoshutiao** [comment]
Hi sergeynk

Sorry for bother you, I have a small question.
Does `Finally, dry deposition sensitivities were not written out correctly.` means dry deposition sensitivities will not wirtten to nc file? or just log file.

bdst

**Comment by sergeynk** [comment]
> Hi sergeynk
> 
> Sorry for bother you, I have a small question. Does `Finally, dry deposition sensitivities were not written out correctly.` means dry deposition sensitivities will not wirtten to nc file? or just log file.
> 
> bds

The deposition sensitivities were not written out the actual output files - "nc" files as you call them. This was addressed in this patch.

Sergey

**Comment by bandaoshutiao** [comment]
> > Hi sergeynk嗨 Sergeynk
> > Sorry for bother you, I have a small question. Does `Finally, dry deposition sensitivities were not written out correctly.` means dry deposition sensitivities will not wirtten to nc file? or just log file.抱歉打扰你，我有个小问题。最后，干沉积敏感性没有被正确地写出。是否意味着干沉积敏感性不会写入数控文件？或者只是日志文件。
> > bdsBDS
> 
> The deposition sensitivities were not written out the actual output files - "nc" files as you call them. This was addressed in this patch.
> 
> 沉积敏感性没有写出实际的输出文件-您称之为“ nc”文件。这个地址在这个补丁里。
> 
> Sergey
> 
> 谢尔盖

Thanks very much

This problem has been bothering me for a long time.

bdst

**Pull request merged**
