### PR TITLE
Fix Lambert Conformal Conic (Tangent Case) 

### PR DESCRIPTION
**Pull request by ramespada**
Hi, 

I noticed that MCIP doesn´t support the Lambert Conformal Conic projection in the specific case where truelat1== truelat2.

The solution was fairly easy the only parameter that needs to be adjusted is the one that you have called ``sinphi0``. I based my solution on [PROJ](https://proj.org/operations/projections/lcc.html) documentation. 

While I have changed the file ``ll2xy_lam_tan.f90`` in order to minimize modifications and so its easier for you to review it, I strongly suggest to merge both ``ll2xy_lam_tan.f90`` and ``ll2xy_lam_sec.f90`` in one file ``ll2xy_lam.f90``  including the following code when ``sinphi0`` is computed:

```fortran
  if ( ABS(phi1 - phi2) > 0.01) then
        sinphi0 = DLOG ( DCOS(phi1rad) / DCOS(phi2rad) )
        sinphi0 = sinphi0 / DLOG (term2 / term1)
  else
        sinphi0 = DSIN(phi1rad)
  endif
```

I am at your disposal if you have any doubt, and I hope I am doing my pull request in the correct branch this time ;)

### CODE REVIEW

**Comment by kmfoley** [comment]
Thank you again @ramespada for reviewing the code and providing these comments.  Our developers will be at a conference all next week but will take a look at the suggested changes in this PR when they return.

**Comment by tlspero** [comment]
Hi @ramespada! Thank you for this proposed consolidation of the Lambert conformal codes. I had intentionally separated them in MCIP and disabled the tangent case (where there is only one true latitude). At the time this part of MCIP was coded, the Spatial Allocator (SA) could not process the single true latitude case because of a divide-by-zero situation. By disabling that variant of Lambert conformal in MCIP, I could conceivably prevent some users with moving forward with a case that could not be supported in the auxiliary codes. However, I'm not sure if that limitation still exists in SA. Regardless, I'll need to look more closely at the code changes that you proposed here. I'm not sure that I will include them, though, particularly if SA still does not support that variant of Lambert conformal. It will be a few weeks before I can get to this, though. Thank you for your patience.

**Comment by tlspero** [comment]
@ramespada, the Spatial Allocator can be obtained from the CMAS Center: https://www.cmascenter.org/sa-tools/. Hope this helps. Looking forward to any additional insight that you can offer.

**Comment by ramespada** [comment]
Ah, I see now. I had initially thought it was a component of CMAQ or MCIP, but it appears to be an optional tool that assists users in preparing input data for CMAQ. If my changes prove to be a viable solution, I hope they can be incorporated into MCIP, regardless of whether works on SA or not. Many users, including myself, do not utilize these tools such as SMOKE, as they are typically tailored for U.S. scenarios. It is my sincere desire to see CMAQ become increasingly adaptable for worldwide applications.

**Comment by tlspero** [comment]
Thank you, again, @ramespada! Your response is very helpful, and it gives me stronger incentive to pursue the changes that you suggested. I'll add them to my list because it seems that MCIP is also unnecessarily restricting the Lambert conformal projection, as well.

To your point about making CMAQ appropriate for worldwide applications, YES! I appreciate your dedication to that aspect. While most of our in-house testing is focused on the Northern Hemisphere and the United States (as you may expect), we do not want to omit the Southern Hemisphere users. Thank you for embracing the "community" of CMAQ and increasing the robustness of the system. I am thankful for all that you are contributing.

**Comment by ramespada** [comment]
Hi! I would like to know if this pull request has been revisited and if there is any intention to correct this failure together with the transverse mercator pull request (#191). Thanks!

**Comment by kmfoley** [comment]
@ramespada I just realized that when I deleted the 5.4+ branch (in conjunction with the 5.5 release) that your PR was closed.  I'm sorry for the inconvenience but would you mind reopening this again on the 5.5+ branch?  @spero May you please provide a response to the question from @ramespada directly above (posted Aug 28).

**Comment by ramespada** [comment]
Hi Kristen, I reopened both the mercator and lcc pull request, I hope someone could take a look to the solution. Thanks!

**Pull request closed without merging**
